package functions

import (
	"context"
	"fmt"
	"log"

	"cloud.google.com/go/firestore"
	firebase "firebase.google.com/go"

	"github.com/Jblew/cairparavel/functions/app"
)

// 	"cloud.google.com/go/firestore"

var application *app.App
var container *container.Container

func init() {
	container.Bind(func() app.Config {
		return GetAutogeneratedConfig()
	})

	firebaseApp, err := firebase.NewApp(context.Background(), &firebase.Config{})
	if err != nil {
		return nil, fmt.Errorf("firebase.NewApp: %v", err)
	}

	container.Bind(func() *firebase.App {
		return firebaseApp
	})

	firestoreClient, err := firebase.Firestore(context.Background())
	if err != nil {
		return nil, fmt.Errorf("app.Firestore: %v", err)
	}

	container.Bind(func() *firestore.Client {
		return firestoreClient
	})

	var err error
	application, err = app.Init(config)

	if err != nil {
		log.Fatalf("Cannot initialize app: %v", err)
	}
}
